name: cicd

on:
  push:
    branches:
      - main
    tags:
      - v*

concurrency:
  # prevent concurrent executions of this workflow
  # we need the dev update to complete before promoting 
  group: ${{ github.workflow }}

jobs:
  update-dev:
    runs-on: ubuntu-latest
    # only runs against commits to the main branch
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: jiridj/wm-apigw-actions-register-api@v1
        with: 
          apigw-url: ${{ secrets.APIGW_URL }}
          apigw-username: ${{ secrets.APIGW_USERNAME }}
          apigw-password: ${{ secrets.APIGW_PASSWORD }}
          api-spec: swagger.json
          set-active: true
          debug: ${{ secrets.ACTIONS_STEP_DEBUG }}

  promote-to-staging:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - id: api-info
        run: |
          API_NAME=$(jq '.info.title' swagger.json | tr -d '"')
          API_VERSION=$(jq '.info.version' swagger.json | tr -d '"')
          echo "::set-output name=api-name::${API_NAME}"
          echo "::set-output name=api-version::${API_VERSION}"
      - uses: jiridj/wm-apigw-actions-promote-api@v1
        with: 
          apigw-url: ${{ secrets.APIGW_URL }}
          apigw-username: ${{ secrets.APIGW_USERNAME }}
          apigw-password: ${{ secrets.APIGW_PASSWORD }}
          api-name: ${{ steps.api-info.outputs.api-name }}
          api-version: ${{ steps.api-info.outputs.api-version }}
          stage-name: staging
          debug: ${{ secrets.ACTIONS_STEP_DEBUG }} 
